# Generated by Django 5.0.2 on 2024-04-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
