# Generated by Django 5.0.2 on 2024-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_playlist_delete_playlist_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('duration', models.FileField(max_length=20, upload_to='')),
            ],
        ),
    ]
