# Generated by Django 5.0.2 on 2024-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_remove_song_audio_link_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='default_value_here', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='static/background.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(default='artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(default='song'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
