# Generated by Django 5.0.2 on 2024-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_song_album_alter_song_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('song_file', models.FileField(upload_to='music/')),
                ('image', models.ImageField(upload_to='images/')),
                ('mp3_file', models.FileField(upload_to='mp3/')),
            ],
            options={
                'db_table': 'Music',
            },
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
