# Generated by Django 5.0.2 on 2024-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default='0:00:00'),
        ),
    ]
