# Generated by Django 5.0.2 on 2024-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
